### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by dbryant4** [dbryant4/furtive#57]
It seems as though there is a memory error when trying to hash a lot of large files. The last file below is 7.5GB and there is ~2.5 GB of RAM free.

Output:
```
Tue Dec  8 02:16:06 2015 EST [DEBUG]: Hash for /smb/Pictures/2011/Flight - Culpeper and Back/940_0182.MOV: cbc95ae47af59137b94ca6786903c440
Tue Dec  8 02:16:06 2015 EST [DEBUG]: Starting Hash of /smb/Pictures/2011/Flight - Culpeper and Back/Merged.wmv
Traceback (most recent call last):
  File "/usr/local/bin/furtive", line 56, in <module>
    main()
  File "/usr/local/bin/furtive", line 50, in main
    furtive.create()
  File "/usr/local/lib/python2.7/dist-packages/furtive/__init__.py", line 35, in create
    self.manifest.create()
  File "/usr/local/lib/python2.7/dist-packages/furtive/manifest.py", line 26, in create
    self.manifest = HashDirectory(self.directory).hash_files()
  File "/usr/local/lib/python2.7/dist-packages/furtive/hasher.py", line 75, in hash_files
    results = pool.map(hash_task, files_to_hash)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
MemoryError
```

**Comment by dbryant4** [comment]
I am guessing that [this line](https://github.com/dbryant4/furtive/blob/master/furtive/hasher.py#L27) is to blame. It's no wonder that the app fails when trying to read in 7.5GB when there is only 2.5GB of available RAM.  It reads in the whole file before hashing. We should switch to a chunk based reading mechanism and try again.

**Comment by dbryant4** [comment]
PR #58 solved this
